services:
  ollama:
    image: ollama/ollama:latest
    container_name: rag-ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "ollama list || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]


  ollama-setup:
    image: ollama/ollama:latest
    container_name: rag-ollama-setup
    depends_on:
      ollama:
        condition: service_healthy
    volumes:
      - ollama_data:/root/.ollama
    environment:
    # base ollama port 11434
      - OLLAMA_HOST=ollama:11434
    entrypoint: ["/bin/bash", "-c"]
    command: 
      - |
        echo 'Waiting for Ollama service to be ready...'
        sleep 10
        echo 'Pulling DeepSeek-R1 model...'
        ollama pull deepseek-r1:8b
        echo 'DeepSeek-R1 model downloaded successfully!'
        echo 'Available models:'
        ollama list
    restart: "no"

  rag-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rag-streamlit-app
    ports:
      - "8502:8501"
    depends_on:
      ollama:
        condition: service_healthy
      ollama-setup:
        condition: service_completed_successfully
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
    volumes:
      - ./data:/app/data:ro
      - ./embeddings:/app/embeddings:ro
      - ./static:/app/static:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  ollama_data:
    driver: local
